title: Manuel Macera
description: Economics — Universidad Torcuato Di Tella
email:

theme: minima
minima:
  skin: classic
  social_links: []

header_pages:
  - index.md
  - research.md
  - teaching.md
  - demographics.md

plugins:
  - jekyll-feed

exclude:
  - scripts/
